//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hemera.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hemera.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string ChartPage {
            get {
                return ResourceManager.GetString("ChartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        public static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an operation.
        /// </summary>
        public static string ChooseOperation {
            get {
                return ResourceManager.GetString("ChooseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days before.
        /// </summary>
        public static string DayBefore {
            get {
                return ResourceManager.GetString("DayBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty).
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Do-Not-Disturb-Mode.
        /// </summary>
        public static string EnableDND {
            get {
                return ResourceManager.GetString("EnableDND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable notification.
        /// </summary>
        public static string EnableNotification {
            get {
                return ResourceManager.GetString("EnableNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be opened.
        /// </summary>
        public static string ErrorOpeningFIle {
            get {
                return ResourceManager.GetString("ErrorOpeningFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freetime.
        /// </summary>
        public static string Freetime {
            get {
                return ResourceManager.GetString("Freetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours before.
        /// </summary>
        public static string HourBefore {
            get {
                return ResourceManager.GetString("HourBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housework.
        /// </summary>
        public static string Housework {
            get {
                return ResourceManager.GetString("Housework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning.
        /// </summary>
        public static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Location not set).
        /// </summary>
        public static string LocationNotSet {
            get {
                return ResourceManager.GetString("LocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as done.
        /// </summary>
        public static string MarkAsDone {
            get {
                return ResourceManager.GetString("MarkAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as missed.
        /// </summary>
        public static string MarkAsMissed {
            get {
                return ResourceManager.GetString("MarkAsMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Duration (Activity).
        /// </summary>
        public static string MaxDurationActivity {
            get {
                return ResourceManager.GetString("MaxDurationActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Duration (Category).
        /// </summary>
        public static string MaxDurationCategory {
            get {
                return ResourceManager.GetString("MaxDurationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes before.
        /// </summary>
        public static string MinuteBefore {
            get {
                return ResourceManager.GetString("MinuteBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup notification.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        public static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planed activity at.
        /// </summary>
        public static string PlanedActivity {
            get {
                return ResourceManager.GetString("PlanedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the recording.
        /// </summary>
        public static string RecordTitle {
            get {
                return ResourceManager.GetString("RecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset status.
        /// </summary>
        public static string ResetStatus {
            get {
                return ResourceManager.GetString("ResetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected position.
        /// </summary>
        public static string SelectedPosition {
            get {
                return ResourceManager.GetString("SelectedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a time.
        /// </summary>
        public static string TimeNeeded {
            get {
                return ResourceManager.GetString("TimeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set a title.
        /// </summary>
        public static string TitleMissing {
            get {
                return ResourceManager.GetString("TitleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
